#!/bin/bash

NAME="docker-mfs-driver"
VERSION="1.0.0"
SRCPATH="/.go/src/github.com/projecteru2"
DIRPATH=`pwd`

mkdir -p $SRCPATH
cp -r $DIRPATH $SRCPATH/$NAME

cd $SRCPATH/$NAME
make build

ROOT="$PWD/build"
BIN="$ROOT/usr/bin"
CONF="$ROOT/etc/sysconfig"
SERVICE="$ROOT/usr/lib/systemd/system"

mkdir -p $BIN
mkdir -p $CONF
mkdir -p $SERVICE

mv $NAME $BIN
cp $NAME.service $SERVICE
cp $NAME.sample $CONF

fpm -f -s dir -t rpm -n $NAME --epoch 0 -v $VERSION --iteration 1.el7 -C $ROOT -p $PWD --verbose --category 'Development/App' --description 'docker mfs driver' --url 'https://github.com/projecteru2/docker-mfs-driver' --license 'MIT' --no-rpm-sign usr etc
cp *.rpm $DIRPATH
